### PR TITLE
Earcanal/master

### PR DESCRIPTION
**Pull request by vsoch**
This PR will include #8 and also updates the CI to use our new container! https://hub.docker.com/r/expfactory/expfactoryr/ sweet!

### CODE REVIEW

**Comment by vsoch** [comment]
hey @earcanal just want to post where I am with this - the tests can be run, but the return code isn't passed on (so the CI doesn't detect when it fails). Eg.,

```

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 0.7 s

OK:       5
Failed:   1
Warnings: 0
Skipped:  0
> 
> 
root@a29b6fc84d9f:/data/expfactory.breathcounting# echo $?
0
```
The above should be some form of nonzero.

**Comment by vsoch** [comment]
okay earcanal this is all you! I can't get the tests to return the correct code, I've made all the changes (see above) and follow the link to see the up to date CI. let me know if / when you want me to try something.

**Comment by earcanal** [comment]
I'm struggling with this too.  I _thought_ I'd found [the way to specify dependencies using roxygen](https://stackoverflow.com/questions/27947344/r-use-magrittr-pipe-operator-in-self-written-package) so that   `@examples` can find what it needs.  But no.  I pushed my latest attempt to #8.

**Comment by earcanal** [comment]
6833a8a968938 might push this forward...?

**Comment by vsoch** [comment]
hey @earcanal ! If you think this is a fix, please PR those changes to the pull request here. Then it will be tested with the changes here. I would start with this base because #8 seems to be farther away from working. Thanks!

**Comment by earcanal** [comment]
Done in #10.

**Comment by vsoch** [comment]
Also @earcanal FYI the license file in the repo is for MIT, not BSD 3 clause :) MIT is more permissive so I'll use that.

**Comment by earcanal** [comment]
Done in #11.

**Pull request merged**
