### PR TITLE
Earcanal/master

### PR DESCRIPTION
**Pull request by earcanal**
Overcome build errors.  Probably.

### CODE REVIEW

**Comment by vsoch** [comment]
Can you see the CI errors / warnings or do you want me to copy paste here? One quick fix for the license, it should be `"BSD 3-clause License"`

**Comment by vsoch** [comment]
```
Undocumented arguments in documentation object 'process_breath_counting'
  ‘json’
Documented arguments not in \usage in documentation object 'process_breath_counting':
  ‘json=TRUE’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
Description
```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
```
included directory?
```
Found the following directory with the name of a check directory:
  ./expfactory.breathcounting.Rcheck
Most likely, these were included erroneously.
```

namespaces
```
* checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: ‘dplyr’
Namespace in Imports field not imported from: ‘tidyverse’
  All declared Imports should be used.
```
```
* checking R code for possible problems ... NOTE
eprime_breath_counting_to_csv: no visible global function definition
  for ‘%>%’
eprime_breath_counting_to_csv: no visible global function definition
  for ‘rowwise’
eprime_breath_counting_to_csv: no visible global function definition
  for ‘do’
eprime_breath_counting_to_csv: no visible binding for global variable
  ‘.’
eprime_breath_counting_to_csv: no visible global function definition
  for ‘write.table’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘%>%’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘rowwise’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘mutate’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘filter’
expfactory_breath_counting_to_csv: no visible binding for global
  variable ‘p’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘do’
expfactory_breath_counting_to_csv: no visible binding for global
  variable ‘.’
expfactory_breath_counting_to_csv: no visible global function
  definition for ‘write.table’
process_breath_counting: no visible global function definition for
  ‘data_frame’
process_breath_counting: no visible global function definition for
  ‘read.csv’
process_breath_counting: no visible global function definition for
  ‘%>%’
process_breath_counting: no visible global function definition for
  ‘filter’
process_breath_counting: no visible binding for global variable
  ‘trial_id’
process_breath_counting: no visible global function definition for
  ‘select’
process_breath_counting: no visible binding for global variable
  ‘trial_index’
process_breath_counting: no visible binding for global variable ‘rt’
process_breath_counting: no visible binding for global variable
  ‘key_press’
process_breath_counting: no visible global function definition for
  ‘mutate’
process_breath_counting: no visible binding for global variable
  ‘Sample’
process_breath_counting: no visible binding for global variable
  ‘response’
process_eprime_file: no visible binding for global variable
  ‘Wait4TUTSlide.RESP’
process_eprime_file: no visible binding for global variable
  ‘Wait4TUTSlide.RT’
process_eprime_file: no visible global function definition for
  ‘add_row’
Undefined global functions or variables:
  . %>% add_row data_frame do filter key_press mutate p read.csv
  response rowwise rt Sample select trial_id trial_index
  Wait4TUTSlide.RESP Wait4TUTSlide.RT write.table
Consider adding
  importFrom("stats", "filter", "rt")
  importFrom("utils", "read.csv", "write.table")
```
and here is complete errors for testing (N=4)
```
test_breath_counting.R:4: error: process_expfactory_bc_file() can process a CSV file
object 'trial_id' not found
1: expect_silent(process_breath_counting("../fixtures/1/1/1_bc.csv", p = 1, json = FALSE)) at /data/expfactory.breathcounting/tests/testthat/test_breath_counting.R:4
2: quasi_capture(enquo(object), evaluate_promise)
3: capture(act$val <- eval_bare(get_expr(quo), get_env(quo)))
4: withr::with_output_sink(temp, withCallingHandlers(withVisible(code), warning = handle_warning, 
       message = handle_message))
5: force(code)
6: withCallingHandlers(withVisible(code), warning = handle_warning, message = handle_message)
7: withVisible(code)
8: eval_bare(get_expr(quo), get_env(quo))
9: process_breath_counting("../fixtures/1/1/1_bc.csv", p = 1, json = FALSE)
10: bc %>% filter(trial_id == "breath_counting") %>% select(trial_index, rt, key_press) %>% 
       dplyr::rename(Sample = trial_index, response = key_press) %>% mutate(Sample = Sample - 
       2, response = ifelse(response == 40, "{DOWNARROW}", "{RIGHTARROW}"), p = p) at /data/expfactory.breathcounting/R/expfactory.breathcounting.R:51
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
12: eval(quote(`_fseq`(`_lhs`)), env, env)
13: eval(quote(`_fseq`(`_lhs`)), env, env)
14: `_fseq`(`_lhs`)
15: freduce(value, `_function_list`)
16: function_list[[i]](value)
17: filter(., trial_id == "breath_counting")

test_breath_counting.R:8: error: expfactory_breath_counting_to_csv() works
could not find function "rowwise"
1: expect_silent(expfactory_breath_counting_to_csv("../fixtures/1", 1, c(2, 6, 7))) at /data/expfactory.breathcounting/tests/testthat/test_breath_counting.R:8
2: quasi_capture(enquo(object), evaluate_promise)
3: capture(act$val <- eval_bare(get_expr(quo), get_env(quo)))
4: withr::with_output_sink(temp, withCallingHandlers(withVisible(code), warning = handle_warning, 
       message = handle_message))
5: force(code)
6: withCallingHandlers(withVisible(code), warning = handle_warning, message = handle_message)
7: withVisible(code)
8: eval_bare(get_expr(quo), get_env(quo))
9: expfactory_breath_counting_to_csv("../fixtures/1", 1, c(2, 6, 7))
10: expand.grid(path = paths, time = t, stringsAsFactors = FALSE) %>% rowwise() %>% mutate(p = as.integer(gsub(".*/.*/(\\d+)/.*$", 
       "\\1", path))) %>% filter(!p %in% exclude) %>% do(., expfactory.breathcounting::process_breath_counting(.$path, 
       .$p, json = FALSE)) at /data/expfactory.breathcounting/R/expfactory.breathcounting.R:16
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
12: eval(quote(`_fseq`(`_lhs`)), env, env)
13: eval(quote(`_fseq`(`_lhs`)), env, env)
14: `_fseq`(`_lhs`)
15: freduce(value, `_function_list`)
16: function_list[[i]](value)

test_breath_counting.R:19: error: process_breath_counting() can process a JSON file
(list) object cannot be coerced to type 'double'
1: expect_silent(process_breath_counting(path, p = 1)) at /data/expfactory.breathcounting/tests/testthat/test_breath_counting.R:19
2: quasi_capture(enquo(object), evaluate_promise)
3: capture(act$val <- eval_bare(get_expr(quo), get_env(quo)))
4: withr::with_output_sink(temp, withCallingHandlers(withVisible(code), warning = handle_warning, 
       message = handle_message))
5: force(code)
6: withCallingHandlers(withVisible(code), warning = handle_warning, message = handle_message)
7: withVisible(code)
8: eval_bare(get_expr(quo), get_env(quo))
9: process_breath_counting(path, p = 1)
10: bc %>% filter(trial_id == "breath_counting") %>% select(trial_index, rt, key_press) %>% 
       dplyr::rename(Sample = trial_index, response = key_press) %>% mutate(Sample = Sample - 
       2, response = ifelse(response == 40, "{DOWNARROW}", "{RIGHTARROW}"), p = p) at /data/expfactory.breathcounting/R/expfactory.breathcounting.R:51
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
12: eval(quote(`_fseq`(`_lhs`)), env, env)
13: eval(quote(`_fseq`(`_lhs`)), env, env)
14: `_fseq`(`_lhs`)
15: freduce(value, `_function_list`)
16: function_list[[i]](value)
17: filter(., trial_id == "breath_counting")
18: as.ts(x)
19: as.ts.default(x)
20: ts(x)
21: data.matrix(data)

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: warning: (unknown)
NAs introduced by coercion

test_breath_counting.R:21: error: (unknown)
(list) object cannot be coerced to type 'double'
1: process_breath_counting(path, p = 1) at /data/expfactory.breathcounting/tests/testthat/test_breath_counting.R:21
2: bc %>% filter(trial_id == "breath_counting") %>% select(trial_index, rt, key_press) %>% 
       dplyr::rename(Sample = trial_index, response = key_press) %>% mutate(Sample = Sample - 
       2, response = ifelse(response == 40, "{DOWNARROW}", "{RIGHTARROW}"), p = p) at /data/expfactory.breathcounting/R/expfactory.breathcounting.R:51
3: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
4: eval(quote(`_fseq`(`_lhs`)), env, env)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
6: `_fseq`(`_lhs`)
7: freduce(value, `_function_list`)
8: function_list[[i]](value)
9: filter(., trial_id == "breath_counting")
10: as.ts(x)
11: as.ts.default(x)
12: ts(x)
13: data.matrix(data)
```

**Comment by earcanal** [comment]
Well CI is certainly earning its keep.  Hopefully all tests should pass this time.

**Comment by vsoch** [comment]
Do the long file paths under fixtures need to be packaged? Or is this something produced / included for the testing?

```
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
expfactory.breathcounting/tests/fixtures/2/00b96573-0f35-4f17-88e4-2836ca7deec1_finished/breath-counting-task-results.json
```
Note that has length 122 so if you changed the uuid to be something shorter, or something like that, you would likely pass testing.

**Comment by earcanal** [comment]
I saw that, but decided to leave as tech debt for now.  It's just a warning, right?

**Comment by vsoch** [comment]
It still is angry about description and license, but differently!

```
Malformed Description field: should contain one or more complete sentences.
License components which are templates and need '+ file LICENSE':
  BSD 3-clause License
 WARNING
```
I would try (given a file named LICENSE, change this appropriately)

```
License: BSD 3-clause License + file LICENSE
```
I still see all of these (truncated)

```
Consider adding
  importFrom("stats", "filter", "rt")
  importFrom("utils", "read.csv", "write.table")
to your NAMESPACE file.
```
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'process_breath_counting'
  ‘json’
Documented arguments not in \usage in documentation object 'process_breath_counting':
  ‘json=TRUE’
```

```
Undocumented arguments in documentation object 'process_breath_counting'
  ‘json’
Documented arguments not in \usage in documentation object 'process_breath_counting':
  ‘json=TRUE’
```
I'm going to let you look at the error outputs and do appropriate changes - ping me when it's ready for review!

**Comment by earcanal** [comment]
I was going to ignore those warnings, but I can take a look if you want them to go away?

I'm not really au fait with license nuances.  Do you have a recommendation?  Once we decide, I think that issue is just a question of ensuring the license file is part of the package.

**Comment by vsoch** [comment]
Yes I believe I gave the suggested string that will fix it.

**Comment by vsoch** [comment]
I would generally give a best effort to address the warnings for the testing.

**Comment by earcanal** [comment]
Sorry, I meant the choice of license, rather than the fix to make the warning go away.  I think I selected "BSD 3-clause" because I saw expfactory use it somewhere.  I have no idea whether it's the best one to use for this code.

**Comment by vsoch** [comment]
okay I'm good to merge here (to update the other branch) and we can go from there.

**Pull request merged**
