### PR TITLE
Earcanal/master

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
@earcanal we need to update the builder to be the one on Quay.io - I cloned your branch and was going to help but you have a totally different CI recipe there. What's up?

**Comment by earcanal** [comment]
I don't think I know anything about the CI recipes. I just push and pray!

**Comment by vsoch** [comment]
Why is the CI recipe (if I clone your master branch here) significantly different?

**Comment by earcanal** [comment]
Different to? (I don't think I understand the question!)

It appears to be the same as

  https://github.com/expfactory-experiments/breath-counting-task/tree/master/.circleci

**Comment by vsoch** [comment]
@earcanal I cloned your master branch to my computer yesterday and this is the config file there 
```yaml
version: 2
jobs:
  build:
    working_directory: /tmp/src
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            cd /tmp/src/
            ls
            cd expfactory.breathcounting
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            echo "Installing package expfactoryr"
            R -e "devtools::install_github('expfactory/expfactory')"
            cd /tmp/src/expfactory.breathcounting
            echo "Running devtools checks and tests for expfactory.breathcounting"
            R -e 'devtools::check()'
            R -e 'devtools::test()'
      - store_artifacts:
          path: /tmp/src/expfactory.breathcounting/man/
          destination: man
```
and the commit history
```
Author: earcanal <paul@miraclefish.com>
Date:   Fri Nov 29 16:55:03 2019 +0000

    Update README.md
    
    Cite Levinson et al.

commit 6833a8a9689389dfd8b16de05a94f3db7cc9c0d5
Author: Paul Sharpe <paul@miraclefish.com>
Date:   Mon Sep 3 13:02:19 2018 +0100

    FIX: Don't run @examples.
    
    I managed to import %>% using @importFrom magrittr "%>%" and including
    magrittr in Depends: (not Imports:).  However, because the example
    depends on having data available I concluded it's best to just wrap it
    in \dontrun{} (see also
    https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies).

commit c885455113b7cbde66f0edd36a70897b715beb43
Author: Paul Sharpe <paul@miraclefish.com>
Date:   Mon Sep 3 12:34:08 2018 +0100

    Try (fail!) to get @examples to build.

commit 029792099671b10affc43d9ed9bc16014b65713b
Author: Paul Sharpe <paul@miraclefish.com>
Date:   Fri Aug 24 15:12:30 2018 +0100

    FIX: CI.

commit 53be3bdeea8e26e650586dbae87de21d02655284
Author: Paul Sharpe <paul@miraclefish.com>
Date:   Fri Aug 24 15:10:35 2018 +0100

    FIX: CI.
```
It looks like I was looking at your master branch and not earcanal/master - why is master different from earcanal/master?

**Comment by vsoch** [comment]
@earcanal I updated the builder to the current (on quay.io) and things look good! Do you want to take a look at my changes, and let me know if they look good and when you are ready to merge with yours?

**Comment by earcanal** [comment]
Ah! Now I see the confusion. I forget why I ended up working on `earcanal/master`, but there was a reason we did this at the time. Is it best to merge that over `master` and remove `earcanal/master`?

**Review by earcanal — COMMENTED** [review]
Looks good as far as I understand CI (i.e. not at all :). :+1:

**Comment by vsoch** [comment]
Since master is the main branch, it would be worth doing a PR from earcanal/master to master, just so the code on master is the latest.

**Comment by vsoch** [comment]
okay, happy to merge then!

**Review by vsoch — APPROVED** [review]

**Pull request merged**
