### PR TITLE
expfactory.breathcounting

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
Awesome! Do you want to add the .circle folder (mimic the other repo where we had testing with expfactoryr) to have the tests run?

**Comment by vsoch** [comment]
I just hooked it up, so if you add a .circleci/config.yml it should kick off --> https://circleci.com/gh/expfactory-experiments/breath-counting-task/1

**Comment by earcanal** [comment]
Done.

**Comment by earcanal** [comment]
I might be starting to understand what you meant by a "base container".  You mean one that has most of the voluminous g++ libs needed by R pre-built?

**Comment by vsoch** [comment]
exactly! The base container would come with all the libraries prebuilt **and** expfactory, so instead of having that looong install we would just run something like:

```bash
docker run vanessa/expfactoryr <testfolder>
```
And then given that the only variable is something like the folder name, if you are developing a repo like this with (some package) folder to be tested, all you have to do is copy paste the entire `.circleci` folder  into your repo, connect to circle and define the variable, and done! 

Does that make sense?

Note that I have a dentist appt I'm running off to, but I'll be back in a bit! I can help make the container and push to Docker Hub and then update the file here if you are up for a little fun :)

**Comment by vsoch** [comment]
hey just an FYI I'm working on the expfactoryr container, will hopefully have a PR for it soonish! I'm struggling with R because it's been a **looong** time, lol.

**Comment by vsoch** [comment]
Closing in favor of #9

**Pull request closed without merging**
